# Generated by Django 3.2.7 on 2021-09-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('botInstance', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, null=True)),
                ('mnensaje', models.CharField(max_length=255, null=True)),
                ('idConversacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversacion')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='idUser1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idUser1', to='chat.user'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='idUser2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idUser2', to='chat.user'),
        ),
    ]
