# Generated by Django 3.2.7 on 2021-09-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mnensaje',
            new_name='mensaje',
        ),
    ]
