# Generated by Django 3.2.7 on 2021-09-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_mnensaje_mensaje_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='query',
        ),
    ]
