# Generated by Django 3.2.7 on 2021-09-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_mensaje_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='idConversacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensaje', to='chat.conversacion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chat.user'),
        ),
    ]
