# Generated by Django 3.2.7 on 2021-09-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_mensaje_idconversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='idUser1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idUser1', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='idUser2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idUser2', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='chat.user'),
        ),
    ]
