# Generated by Django 3.2.7 on 2021-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210929_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='idConversacion',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
