# Generated by Django 3.2.7 on 2021-10-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210930_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversacion',
        ),
    ]
