# Generated by Django 3.2.7 on 2021-10-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_delete_conversacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
    ]
