# Generated by Django 3.2.7 on 2021-10-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_nombre_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mensaje',
            new_name='message',
        ),
    ]
